<?php
/*
 * Possible templates
    nextActive The active state for a link generated by next().
    nextDisabled The disabled state for next().
    prevActive The active state for a link generated by prev().
    prevDisabled The disabled state for prev()
    counterRange The template counter() uses when format == range.
    counterPages The template counter() uses when format == pages.
    first The template used for a link generated by first().
    last The template used for a link generated by last()
    number The template used for a link generated by numbers().
    current The template used for the current page.
    ellipsis The template used for ellipses generated by numbers().
    sort The template for a sort link with no direction.
    sortAsc The template for a sort link with an ascending direction.
    sortDesc The template for a sort link with a descending direction.
 */

return [
    'nextActive' => '<li class="paginate_button page-item next" id="datatables_next"><a href="{{url}}" aria-controls="datatables" data-dt-idx="2" class="page-link">{{text}}</a></li>',
    'nextDisabled' => '<li class="paginate_button page-item next disabled" id="datatables_next"><a href="{{url}}" aria-controls="datatables" data-dt-idx="7" class="page-link">{{text}}</a></li>',
    'prevActive' => '<li class="paginate_button page-item previous" id="datatables_previous"><a href="{{url}}" aria-controls="datatables" data-dt-idx="1" class="page-link">{{text}}</a></li>',
    'prevDisabled' => '<li class="paginate_button page-item previous disabled" id="datatables_previous"><a href="{{url}}" aria-controls="datatables" data-dt-idx="1" class="page-link">{{text}}</a></li>',
    'first' => '<li class="paginate_button page-item first" id="datatables_first"><a href="{{url}}" aria-controls="datatables" data-dt-idx="0" class="page-link">{{text}}</a></li>',
    'last' => '<li class="paginate_button page-item last" id="datatables_last"><a href="{{url}}" aria-controls="datatables" data-dt-idx="{{count + 3}}" class="page-link">{{text}}</a></li>',
    'current' => '<li class="paginate_button page-item active"><a href="{{url}}" aria-controls="datatables" data-dt-idx="{{count}}" tabindex="0" class="page-link">{{text}}</a></li>',
    'number' => '<li class="paginate_button page-item"><a href="{{url}}" aria-controls="datatables" data-dt-idx="{{count}}" tabindex="0" class="page-link">{{text}}</a></li>'
];
